add_executable(ejercicio_1 ejercicio_1/main.c)
add_executable(ejercicio_2 ejercicio_2/main.c)
target_link_libraries(ejercicio_2  PRIVATE fixed_point)
add_executable(ejercicio_3 ejercicio_3/main.c)
target_link_libraries(ejercicio_3  PRIVATE fixed_point)
add_executable(ejercicio_4 ejercicio_4/main.c)
target_link_libraries(ejercicio_4  PRIVATE fixed_point)
add_executable(ejercicio_5 ejercicio_5/main.c)
target_link_libraries(ejercicio_5  PRIVATE fixed_point)